#SkyBlock configuration
#Protection from getting killed on skyblock
death-protection: false
#Void fall protection
void-fall-protection: true
#Create default kits and schemes
create-default-files: true
#Item in hand for selecting points
wand-material: 'WOODEN_AXE'
#Where to teleport players who leave skyblock. WORLD_SPAWNPOINT or CUSTOM_SPAWNPOINT(/sb setcustomspawn).
spawn-point: 'WORLD_SPAWNPOINT'
#Kits settings
kits:
  show-only-available: false
  show-limits: true
#Schemes settings
schemes:
  show-only-available: false
  show-limits: true
#Free kits
free-kits:
- defaultKit
- farmer
#Free schemes
free-schemes:
- defaultScheme
#Send title?
send-titles: true