#TODO
wand-material: 'WOODEN_AXE'
spawn-point: 'WORLD_SPAWNPOINT'
kits:
  show-only-available: false
  show-limits: true
schemes:
  show-only-available: false
  show-limits: true
free-kits:
- defaultKit
- farmer
free-schemes:
- defaultScheme