name: SkyBlock
main: org.Bukkitters.SkyBlock.Main
version: 1.0
description: aaa
authors: [NukerFall, Soyer]
api-version: 1.16
commands:
  skyblock:
    description: SkyBlock main command.
    aliases: [sb, sblock, скайблок, blocksky]