name: SkyBlock
main: org.Bukkitters.SkyBlock.Main
version: 1.1-BETA
description: SkyBlock plugin
authors: [NukerFall, Soyer]
api-version: 1.16
depends: [Vault]
commands:
  skyblock:
    description: SkyBlock main command.
    aliases: [sb, sblock]